### POST Create new short url
POST http://localhost:5000/shorten
Content-Type: application/json

{
	"longUrl": "http://www.sennheiser.com.pl/sluchawki-domowe-i-hifi-sennheiser.html"
}

### GET original url
GET http://localhost:5000/zO-EoJ3WW