### POST Create new short url
POST http://localhost:5000/shorten
Content-Type: application/json

{
	"longUrl": "https://www.npmjs.com/package/express-limiter"
}

### GET original url
GET http://localhost:5000/zO-EoJ3WW