### POST Create new short url
POST http://localhost:5000/api/shorten
Content-Type: application/json

{
	"longUrl": "https://youtu.be/0XjEAXu5Cc8?list=WL&t=540"
}

### GET original url
GET http://localhost:5000/api/PoijSJnPB

### GET 5 latest urls
GET http://localhost:5000/api